<?php
echo '<?php';
echo "\n";
echo "\n";
echo 'final class PZ_Config';
echo "\n";
echo '{';
echo "\n";

echo 'const MERCHANT_ID = ';
echo '"'.$settings['MERCHANT_ID'].'"';
echo ';';
echo "\n";
echo 'const SECRET_KEY = ';
echo '"'.$settings['SECRET_KEY'].'"';
echo ';';
echo "\n";
echo 'const TRANSACTION_TYPE = ';
echo '"'.$settings['TRANSACTION_TYPE'].'"';
echo ';';
echo "\n";
echo 'const CURRENCY = ';
echo '"'.$settings['CURRENCY'].'"';
echo ';';
echo "\n";
echo 'const UI_MODE = ';
echo '"'.$settings['UI_MODE'].'"';
echo ';';
echo "\n";
echo 'const HASH_METHOD = ';
echo '"'.$settings['HASH_METHOD'].'"';
echo ';';
echo "\n";
echo 'const MERCHANT_KEY_ID = ';
echo '"'.$settings['MERCHANT_KEY_ID'].'"';
echo ';';
echo "\n";
echo 'const CALLBACK_URL = ';
echo '"'.$settings['CALLBACK_URL'].'"';
echo ';';
echo "\n";
echo "\n";
echo 'const API_BASE = ';
echo '"'.$settings['API_BASE'].'"';
echo ';';
echo "\n";
echo 'const API_CHARGING = ';
echo '"'.$settings['API_CHARGING'].'"';
echo ';';
echo "\n";
echo 'const API_QUERY = ';
echo '"'.$settings['API_QUERY'].'"';
echo ';';
echo "\n";
echo 'const API_REFUND = ';
echo '"'.$settings['API_REFUND'].'"';
echo ';';
echo "\n";
echo 'const API_VERSION = ';
echo '"'.$settings['API_VERSION'].'"';
echo ';';
echo "\n";
echo 'const VERIFY_SSL_CERTS = ';
echo '"'.$settings['VERIFY_SSL_CERTS'].'"';
echo ';';
echo "\n";
echo "\n";
echo '}';
echo "\n";
echo '?>';

?>